# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPjt6hV1SHVmUWh8UACO4u3gid3ZERvp
"""

a = input().split()
count = 0
for i in a:
  if int(i) < 60:
    count = count + 1
print(count)